### ISSUE TITLE
Investigate new recaptcha thing

### ISSUE THREAD

**Issue by afuna** [dreamwidth/dreamwidth#1108]
http://googleonlinesecurity.blogspot.com/2014/12/are-you-robot-introducing-no-captcha.html <-- 
- see if it works well enough we can switch our existing recaptcha implementation over, or if we should offer it as another option instead but keep old recaptcha
- see if it works well enough we should use it as our default captcha

**Comment by afuna** [comment]
> * see if it works well enough we can switch our existing recaptcha implementation over, or if we should offer it as another option instead but keep old recaptcha

I think better if we just replace so we have two captcha possibilities instead of three. We'd have to rename "image captcha" to something else though. checkbox captcha? simple captcha?

> * see if it works well enough we should use it as our default captcha

Feedback from a11y folks is mixed; think it doesn't work with all setups* of screenreader + browser but surprisingly, for me at least, looks to work with keyboard. The way it was announced led me to think it was mouse-only.

http://simplyaccessible.com/article/googles-no-captcha/ (positive)
http://www.webaxe.org/google-no-captcha-some-progress/ (says doesn't work with js / mobile)

* annoyingly I can't find the specific article where this was tested

**Comment by momijizukamori** [comment]
I am gonna close this for now because captcha tech has changed a TON in the last seven years, and we will probably need to start any investigation over fresh now.
