### ISSUE TITLE
document icon expiring rules

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dreamwidth#1288]
I see persistent confusion about this (people think it's "default icon + 14 most recently uploaded icons" because they never make posts in their own journal, which is the only thing that script looks at for counting usage) so this is a note to self for me to write a FAQ explaining that.

**Comment by rahaeli** [comment]
From the explanation I wrote just now while rejecting another suggestion for "don't automatically pick the most recently uploaded icons to remain active when an account expires", for cribbing later and turning into FAQ-style language:


> The rule for picking which icons to deactivate when an account expires isn't the default icon + the 14 newest icons -- it can just often look that way because of the way RPers tend to use their accounts. (That is to say, mostly posting and commenting in communities, rather than in their personal journals.) The paid account expiration script chooses the 15 icons that have been used most often in entries to the user's personal journal only -- not taking community posts or any comments (in your account, in other accounts, or in communities) into account for the calculations. (The reason why is boring and technical, so I won't explain it, but there are very good performance reasons for doing it that way and it wouldn't be possible to change!)

> If fewer than 15 icons have been used on entries, or fewer than 15 entries have been posted in the journal, the script falls back to choosing the default icon and then the most recently uploaded icons. (The same thing happens if there's a tie in the number of times several icons have been used: the script defaults to choosing the newest icons. So if you have 14 icons that have all been used twice, and then 30 icons that have each been used once, the script will pick the newest of those 30 icons for the 15th slot.) If you rarely or never post to your own account, that results in the behavior you've noticed.

> So, it's possible to force the paid account expiration script to pick the icons you want to keep active -- it just takes a few minutes of setup when you first create the account. (Or you can do it at any time, really, such as when you get the "your account will be expiring in three days" email to remind you.) What you'll need to do is pick the 15 icons you want to keep active, then make 15 posts to your personal journal (not to a community). The posts don't have to be public: you can post them locked or private if you want. Make sure that each entry is using one of the icons you want to keep active. If those are the only posts you've made to your journal, the account expiring script will see that your account has one use of each of those 15 icons, and no uses of any other icons, so it'll keep those icons active while deactivating the others. 

> If you have other posts in your journal, of course, that will increase the usage count for whatever icon you used in those posts, so you'll have to take that count into account when you're doing your setup. For instance, if you have an icon keyworded 'hello' that you've used on four posts to your journal, but you don't want that icon to stay active when your paid account expires, you'd have to post five posts each with the fifteen icons you want to keep active, so that their usage count is higher than the icon you don't want.

**Comment by rahaeli** [comment]
NB, now that I look at that I'm actually not 100% sure on the "they can be private posts" part. Must confirm.

**Comment by kareila** [comment]
Someone just pointed out to me that we do have a paragraph in https://www.dreamwidth.org/support/faqbrowse?faqid=227 describing which icons are deactivated. It's not as detailed as what's written here, but is it sufficiently correct to close this?

**Comment by kareila** [comment]
I've updated [FAQ 16](https://www.dreamwidth.org/support/faqbrowse?faqid=16) with a one-paragraph version of this explanation, which I think will be sufficient. That's the top FAQ search hit for "icon" so I believe it's more likely to be seen there than in the account expiration FAQ. People can ask support volunteers for the longer explanation if they're still confused.
