### ISSUE TITLE
Foundation Create Entries beta has display issues in some combinations of *nix and Iceweasel

### ISSUE THREAD

**Issue by kaberett** [dreamwidth/dreamwidth#1336]
I am running Iceweasel under Debian Jessie on all of my machines.

On my desktop (Iceweasel 31.2) the post-push Create Entries page is clearly working as intended.

On my laptop (Iceweasel 31.3) it isn't. Screenshot at http://lib.rett.org.uk/~alex/images/misc/dreamwidth-update.png

Issues:

(1) Note that my userpic (top right, page header) overlaps with the menu bar. This does /not/ happen on other site-schemed pages (or at least doesn't happen on dreamwidth.org).

(2) Tags widget. Note that any entered tag displays as "tag Remove [tag]". (There's only one example, but it does this with all of 'em). On my desktop machine (31.2) instead of the text "Remove [tag]" I see a small cross image instead (per previous behaviour).

Doing a hard refresh doesn't get me the image instead. Thoughts? I recognise this one's going to be a pain to track down...

-- and it's still an issue in 31.5, again, on my laptop but not my desktops.

**Comment by woggy** [comment]
claimed. (though i haven't a clue how to begin troubleshooting this, and am more than open to suggestions/pointers/etc)

**Comment by kaberett** [comment]
I'm actually no longer getting this issue (no idea how much this is because I moved away from using the machine it was happening on), so closing this!

**Comment by kaberett** [comment]
Apparently @woggy is now seeing this? So re-opening.

**Comment by woggy** [comment]
To clarify: I'm only seeing the issue with the tag widget, though it's identical in form. Win7, Opera 39.0

**Comment by momijizukamori** [comment]
I think this has been solved by browser changes and other updates in the five years since this was last touched, so I'm closing for now!
