### ISSUE TITLE
/tools/tellafriend needs a rewrite

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dreamwidth#1866]
Right now it uses the validated email address of the logged in user, which doesn't work with sending email via SES.  It should send email instead from dw_null@dreamwidth.org, like our other notifications do.  The page has other problems too, and should probably be completely revamped.

More changes I would like to see:
- From: userhead (instead of `name <email address>`) along with explanatory text saying the user's authenticated email address will be used as the reply-to of the sent message (or their site alias, if their account has that feature).
- Make the textarea the full size of the page instead of a tiny box within a box.
- Update or remove the supplied text, e.g. when clicking tellafriend from another user's journal: "Hey, Check out my friend's journal online:" or even worse, from your own journal: "Dear Here's a link to the journal that I'm keeping online:"
- Fix the footer to use $LJ::NEWS_JOURNAL - right now it says to visit news.dreamwidth.org
- Add the page to the list of pages that should block web spiders - the access log is crammed full of bogus page hits because there are so many links to it.

**Comment by srukle** [comment]
@kareila 

For the page format, is there a DW page that is formatted similarly that you'd like to see? When you say "full-page," I just need some clarity. 

In the first point, is this what you're looking for:

```From: (icon) user <This will be replaced by your authenticated email address>```

Would the explanatory text be located on that same line? Wouldn't that be clunkier than having something like this:

```From: (icon) user<email>```

Or should there be an icon that refers the user to a footer on the page? Something like this:

```From: (icon) user 

* You authenticated email will be sent with this email.```

Thanks! :smile:

**Comment by kareila** [comment]
Just an update to point out that 2bcca87a087cd5715e77fcfb0e2a0b7f5589aff1 converted this to TT, but I haven't looked to see if it incorporated any of the above suggestions, and it looks like the BML page hasn't actually been removed from the repository yet.
