### ISSUE TITLE
Previously administered community still listed in Manage Communities

### ISSUE THREAD

**Issue by ninetyd** [dreamwidth/dreamwidth#2188]
Might be just me, but I used to admin tv_talk and it's still listed at Manage Communities. Just the name, though. The rest of the table is empty. I'm no longer either a subscriber or a member of this comm. It is not listed in Manage Circle or in workas menus but it also shows up in the list of accounts I can post to on Create Beta.

Feel free to poke around my account if needed.

**Comment by kareila** [comment]
This was eventually resolved in support: https://www.dreamwidth.org/support/see_request?id=42903
