### ISSUE TITLE
Add Google Drive to embeds whitelist

### ISSUE THREAD

**Issue by kaberett** [dreamwidth/dreamwidth#2196]
https://www.dreamwidth.org/support/see_request?id=36912

Sample code: 
`<iframe src="https://drive.google.com/file/d/0B65w91gNVFP0OFVsMGxpVmlvRzA/preview" width="640" height="480"></iframe>`

**Comment by kaberett** [comment]
Another request: https://www.dreamwidth.org/support/see_request?id=38076

**Comment by rshatch** [comment]
I'm going to do some investigating into what Drive considers 'embeddable', because you can upload arbitrary files and I'm not sure we'd want to allow embedding of everything? Depends on the formatting I guess.
