### ISSUE TITLE
Location: Edinburgh, (Error in linkification)

### ISSUE THREAD

**Issue by kaberett** [dreamwidth/dreamwidth#2197]
https://www.dreamwidth.org/support/see_request?id=36930: 
> I see this on all the profiles of the accounts in search results of
http://www.dreamwidth.org/directorysearch?loc_ci=Edinburgh&loc_cn=LJSC&opt_sort=ut&s_loc=1&start_search=1

Possibly related to #1623?

**Comment by kareila** [comment]
The code tour referenced in the support request refers to http://changelog.dreamwidth.org/789751.html which doesn't seem exactly relevant? Sharing anyway in case it proves helpful.

**Comment by pauamma** [comment]
At a guess, I would say this is related to bug #842, which removed LJSC as a "country".
