### ISSUE TITLE
currency formatting glitch when paying by check/MO in shop

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dreamwidth#2328]
https://www.dreamwidth.org/support/see_request?id=38431

After submitting an order, "Amount Due" is listed as "$XX.X USD" with one place after the decimal point instead of two.

**Comment by kaberett** [comment]
I'm not reproducing this -- I have put together something that forces 2 decimal places but it doesn't appear to change the behaviour I'm seeing...

Is it still happening? Can I have more detailed steps-to-reproduce? (I don't have the privs to see the support request.)

**Comment by kareila** [comment]
I pasted in the text of the support request more or less verbatim - there were no further details given, but I did some digging and can tell you that the user was buying points, if that helps. (I was going to add that the amount of the purchase ended in a zero, but I think that's true for every purchase.)
