### ISSUE TITLE
additional external sites: FurAffinity and ArtStation

### ISSUE THREAD

**Issue by kaberett** [dreamwidth/dreamwidth#2455]
Support request for additions to `<user>` tag and Other Sites: https://www.dreamwidth.org/support/see_request?id=39572

Furaffinity:
- `<user>`: Url for the "journal" part: https://www.furaffinity.net/gallery/username/ | Url for the "profile" part: https://www.furaffinity.net/user/username/
- profile: needs username, links to: https://www.furaffinity.net/user/username/

ArtStation:
- `<user>`: Url for the "journal" part: https://www.artstation.com/username | Url for the "profile" part: https://www.artstation.com/username/profile
- profile: needs username, links to: https://www.artstation.com/username

**Comment by rahaeli** [comment]
Hmmm. I know FurAffinity is kind of niche; I'm wondering if we should add it. How big is ArtStation? I haven't heard of them, but I'm not a visual artist so that's not unusual...

**Comment by kaberett** [comment]
Not super familiar with ArtStation, but I didn't think FurAffinity was any more niche than Ravelry? [rummages]
