### ISSUE TITLE
Compressed comment subjects are displayed as raw gzip data

### ISSUE THREAD

**Issue by alierak** [dreamwidth/dreamwidth#2524]
With removal of the $LJ::COMPRESS_TEXT option, LJ::text_compress will now gzip things, where it was previously optional. Comment subjects are one of those things, when a comment is edited (see _set_text() in cgi-bin/LJ/Comment.pm), but comment subjects are not ever uncompressed when being loaded from the db. Raw gzip data can be displayed, as in https://bakerstreet.dreamwidth.org/5797832.html?thread=2541398728#cmt2541398728

**Comment by nfagerlund** [comment]
I wish you could have seen the look on my face reading this issue description

**Comment by alierak** [comment]
Not only that, I think to run into this issue your comment subject has to be exactly 100 characters long before compression and shorter than that after compression. And to see it in action, after editing, you have to wait for it to age out of memcache so the raw form is loaded from the db.

**Comment by nfagerlund** [comment]
My dude, I am dying over here, what the HECK

**Comment by alierak** [comment]
So I guess the question is, do we nuke it with fire, quit trying to save a byte on compressed 100-char edited subjects, and fix the few oddballs that made it into the db (yay!); or do we implement uncompression whenever a comment subject is loaded (boo!)?

**Comment by zorkian** [comment]
What's the objection to just always compressing/decompressing?

I don't think we need to really, but I'm not too concerned about CPU usage on zlib.
