### ISSUE TITLE
Foundation login form needs to grab keyboard focus?

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dreamwidth#2798]
I just noticed on a Foundation page, after clicking "Log In", I had to hit the tab key four times to focus the user name field. Not my area of expertise, but shouldn't popping up the login form grab the keyboard input focus?

(The first three tab hits were the search box, search type select, and Go button in the navbar, which is partially hidden behind the login form that pops up.)

**Comment by kareila** [comment]
Related but possibly a separate issue: if you have the window shrunk down to mobile size and are logged out, hitting tab into the search box covers the login link and I don't see a way to get it back without reloading the page.

**Comment by nfagerlund** [comment]
Lol, that definitely sucks. 

On desktop at least, it's a bummer to use a modal for this in the first place. I can sort of see it on mobile, but to be honest I generally prefer disclosure interactions for that sort of thing than modal dialogs. (That requires you to know what the content is being revealed into, though; not always practical in the first place \[cf. the icon browser\], and of course authors of frameworks like foundation aren't going to know _anything_ about your page, so makes sense that _they'd_ prefer a drop-it-and-forget-it solution like an absolutely positioned modal.)

But never mind that. Anyway: foundation's reveal modal doesn't have any support for focusing an element after opening. I implemented that for the icon browser, though -- you have to bind a function to the... I think it's the "foundation.reveal.opened" event, would have to look it up. 

- We could add a special event handler just for the login button — gross, but how many other modals do we still have, after that and the icon browser? Hmm, looks like it's the mobile "account links" thing (logout, inbox, etc.), and a bunch of stuff on the create entries page.
- Actually though, all of those modals completely suck for dealing with keyboard focus. They all leave the tab focus out wherever you left it by clicking the button, and the modals themselves are all punted to the end of the document during setup, so you need to tab through EVERYTHING. So, maybe we want a general solution where the modal or its trigger can use a data attribute to specify a raise focus target and a dismiss focus target. Easy enough to do that with a global handler, I think.

**Comment by kareila** [comment]
This has come up again now that the homepage has been converted to Foundation.

https://dw-maintenance.dreamwidth.org/92733.html?thread=4202301#cmt4202301

**Comment by kareila** [comment]
I've tried digging into this and it looks to me like the script `htdocs/js/skins/jquery.focus-on-reveal.js` is *supposed* to adjust the keyboard focus when the form is revealed, but it doesn't seem to be triggering, and I'm at a loss to figure out why.

**Comment by momijizukamori** [comment]
I'll go digging into the JS and see what I can find.

**Comment by momijizukamori** [comment]
Okay, so it turns out that `jquery.focus-on-reveal.js` didn't have the correct events bound, and changing that fixed it, though I then discovered that the modal close button isn't keyboard-focusable for some reason, so I'm poking at that.
