### ISSUE TITLE
check for etc/config.pl

### ISSUE THREAD

**Issue by martindemello** [dreamwidth/dreamwidth#2897]
If `etc/config.pl` is missing, `bin/checkconfig.pl` fails with

```
dw@dev-width:~/dw$ bin/checkconfig.pl 
[Checking LJ Environment...]

Problem:
  * No file found for etc/config.pl
```

however, `etc/config.pl.example` says

```
# LiveJournal configuration file.

# THIS FILE IS INTENDED FOR EXAMPLE/DOCUMENTATION PURPOSES ONLY.

# Ideally, any configuration changes for your site should go in
# config-local.pl or config-private.pl.  If you feel like you need
# a site-specific config.pl, make sure you copy it to ext/local/etc
# and customize it there.  This will protect it from getting clobbered
# when you upgrade to the newest Dreamwidth code in the future, but
# you will not automatically inherit additions or updates to this file.
```

So what is the intended purpose of `etc/config.pl`? And for development purposes is simply `cp etc/config.pl.example etc/config.pl` fine or will it create issues?

**Comment by kareila** [comment]
I believe that when `etc/config.pl` was renamed to `etc/config.pl.example` the boilerplate text was not updated. I added the check to `bin/checkconfig.pl` to help occasional developers who had previously expected `etc/config.pl` to be there and didn't realize they needed to make a renamed copy of the example file.

You should make a copy of the file in your `ext/local/etc` directory, same as for `config-local.pl` or `config-private.pl`, to avoid accidentally including a copy of the file with your intended changes.

Leaving this open to indicate that the boilerplate text should be updated for current practices.

**Comment by martindemello** [comment]
thanks! so is the app using `etc/config.pl` at all, or is `ext/local/etc/config.pl` the only place it gets that configuration from?

**Comment by kareila** [comment]
If etc/config.pl exists it can be used, but the local version is preferred,
and if both exist, the local version will be chosen.

**Comment by martindemello** [comment]
would it make sense for `checkconfig.pl` to look for `ext/local/etc/config.pl` instead?

**Comment by kareila** [comment]
It checks both places, as defined in the `LJ::resolve_file` subroutine.
