### ISSUE TITLE
shop receipts incorrectly report multiple purchases of same item

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dreamwidth#2916]
Someone bought the "12 months of premium paid time" twice (for 2 years total of premium paid time) in a single cart. The email they got was:

> Your Dreamwidth Studios account has been upgraded.
>
> The account type that was purchased is:
>
> Premium Paid Account for 12 months
>
> Congratulations on your paid time! You can see a list of all the premium
> features you now have access to here:

This confused them and they wrote in to check that they'd actually gotten credit for both the years they bought. If someone buys multiples of any item in the same order, we should indicate the multiples somehow, either as 

> 2 - Premium Paid Account for 12 months

or 

> Premium Paid Account for 12 months
> Premium Paid Account for 12 months

And I started to add another change that could help avoid the confusion but immediately realized there are eight billion edge cases that it probably can't easily piggyback on this change, I'll open a separate issue for  it

**Comment by kareila** [comment]
These emails are generated per cart item processed, not per cart, and there's no way to consolidate them without a significant rewrite. This is enough of an edge case that I don't think it's worth the effort.
