### ISSUE TITLE
shop emailed receipts should show new expiration date of paid time for your own accounts

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dreamwidth#2917]
If the purchase you just made was for your own account, the receipt email should include, just after the items purchased and just before the "Congratulations on your paid time!", your current paid time expiration date:

> Your Dreamwidth Studios account has been upgraded.
>
> The account type that was purchased is:
>
> Premium Paid Account for 12 months
>
> Your new paid time expiration date is: [[date]]
>
> Congratulations on your paid time! You can see a list of all the premium
> features you now have access to here:

"Is this purchase for your own account" is kind of harder than just saying a basic "is the account that is receiving the paid time the same as the account that made the purchase", given how often someone with a bunch of accounts is buying paid time for all of them at once. I think this information is not incredibly sensitive and a basic "does the account that's getting the paid time have the same current confirmed email address as the account that bought the paid time" will suffice.

**Comment by kareila** [comment]
It looks like the text of the message you're referencing isn't sent to the address of the person who made the purchase. Rather, it's sent to the address of the owner of the account that got upgraded (or, in the case of a community, the maintainers of that community) when the paid time is applied - so permission checks aren't actually needed here.
