### ISSUE TITLE
"edit this FAQ" link disappeared at some point

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dreamwidth#2925]
Way back in the dawn of time, people with faqedit privs would see an "edit this FAQ" link at the bottom of every FAQ, so you could go straight to editing the FAQ if you spotted a problem. it is no longer there! we should put it back.

**Comment by pauamma** [comment]
Looks like it's still there (https://github.com/dreamwidth/dw-free/blob/63a6ff463f793831ac323c567e53d778a73b226d/views/support/faqbrowse.tt#L73). I'm not sure whether/how remote.has_priv is wrong, but if a change to LJ::User::Permissions had broken it, I think someone (including you and me) would have noticed in short order.

**Comment by rahaeli** [comment]
Hmm. I definitely do not see the edit link while logged in as denise, who has faqedit:*. I also tried with just plain faqedit (no *) and with the individual category args (ie, faqedit:issues and then looking at a faq in the issues category) and neither of those worked either. Tried in two separate browsers, too.

**Comment by kareila** [comment]
In cgi-bin/DW/Controller/Support/Faq.pm in the `faqbrowse_handler` function, I can see that it is missing a statement `$vars->{remote} = $remote;` anywhere before calling `render_template`, so the template never has a valid remote to act on.

**Comment by rahaeli** [comment]
Oho! That would do it, yes.

**Comment by pauamma** [comment]
> Hmm. I definitely do not see the edit link while logged in as denise, who has faqedit:*.
My sloppy writing. I meant the attempt to display it is still present, so the problem must be elsewhere.
