### ISSUE TITLE
change DW's Google Analytics snippet to use GA4

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dreamwidth#2955]
Not the user-facing GA feature (that's in #2954) but the DW production GA code on site-skinned pages needs to be updated. The code that needs to be swapped in for the old GA code is:

    
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-4FH9Y1TDGT"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
    
      gtag('config', 'G-4FH9Y1TDGT');
    </script>

That's got the DW identifier in it already (G-4FH9Y1TDGT). I've already done the thingamajig with the Google account itself so we should be able to start getting data if we just update the code.

**Comment by momijizukamori** [comment]
For ref in my digging - for site pages, we store the identifier value in the `SITE_PAGESTAT_CONFIG{google_analytics }` config value in `config-private.pl`.

This is then used in https://github.com/dreamwidth/dw-free/blob/950b1e9777e6f814fa518e74831943c3f98d7df6/cgi-bin/DW/PageStats/GoogleAnalytics.pm which actually has the code for building the rest of the script tag.
