### ISSUE TITLE
login redirect problem with URL-escaped characters

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dreamwidth#2960]
I was trying to leave a comment on a URL that ended with `?mode=reply` when I realized I wasn't logged in and used the control strip form to do so. When I submitted the form, I was redirected to the escaped URL ending in `%3Fmode%3Dreply` which resulted in a 404 page.

**Comment by momijizukamori** [comment]
This has been low-key irritating me too, so I will do some digging when I have brainpower. It's probably related to https://github.com/dreamwidth/dw-free/pull/2889 where we changed the redirect behavior to not use referrer sniffing because it didn't work in all browsers.

**Comment by kareila** [comment]
Another report says logging out has the same problem: https://www.dreamwidth.org/support/see_request?id=46162
