### ISSUE TITLE
FAQ 51 wording nits

### ISSUE THREAD

**Issue by pauamma** [dreamwidth/dreamwidth#2972]
- "the date you last posted to your account" should read "to your journal", both for accuracy and for consistency with "the number of entries you've made to your journal"
- conversely, "the number of entries you've made to your journal" should be "you've posted" for consistency with the above
- "the number of memorable entries you've memoried" feels repetitive, and is "committed to memory"/"made into a memory" a sense of "memoried"? I would use "memorized" or perhaps "memorialized" for that, and MW only gives "remembered" (so not necessarily deliberate) as the closest meaning in https://www.merriam-webster.com/dictionary/memoried. AHD doesn't have it, and Wiktionary (https://en.wiktionary.org/wiki/memoried) says that meaning is obsolete, with a quote 200 years ago.

**Comment by kareila** [comment]
edited
