### ISSUE TITLE
Missing "all lowercase" mention and misleading mixed-case interest examples in FAQ 14

### ISSUE THREAD

**Issue by pauamma** [dreamwidth/dreamwidth#2973]
There's no mention that all interests are made lowercase, and the "Italian Opera", "New Wave Punk", "Wagner" and "Metallica" examples wrongly imply the opposite. (While there, maybe make them into a proper inline list with "or" only before the last item.)

Tangentially, when was the interest casefolding generalized to Unicode? I just added Νίκος Καζαντζάκης and Καζαντζάκης, which became νίκος καζαντζάκης and καζαντζάκης, but IIRC, LJ would only do that for ASCII.

**Comment by kareila** [comment]
edited FAQ to mention lowercasing
