### ISSUE TITLE
Make cut links targetable by CSS

### ISSUE THREAD

**Issue by momijizukamori** [dreamwidth/dreamwidth#2979]
The actual expand/collapse arrow has a class added to it, but the text elements do not, so if you want to do any cut-specific styling, you have to do some funky stuff with sibling CSS selectors that is very unintuitive. Cut text is generated before it reaches the level of user-editable S2 layers, too, so you can't override it at a layer level.

**Comment by cmho** [comment]
oh good i was just in fact doing some funky stuff to style cut tags. claiming
