### ISSUE TITLE
the "timecheck" column in the "userusage" table is unused

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dreamwidth#2985]
Should we drop the column from the database? Not sure why it was included in the first place.

**Comment by rahaeli** [comment]
It was imported from LJ, where it was committed on Aug 18, 2001 (https://github.com/rahaeli/livejournal/commit/9e3ab4ad97e60371ecf942206e6fe9efe19f2806) so I think it's probably safe by now to delete if nothing uses it!
