### ISSUE TITLE
create worker script to clean up discarded shopping carts

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dreamwidth#3009]
@zorkian remarked recently when migrating databases that the carts table was gigantic, and that we should clean it up occasionally. I noticed that as well when I was testing my recent shop changes - a new row in the table is created every time anyone visits the page, basically.

I propose removing any "open" carts that are older than 30 days.

<img width="967" alt="Screen Shot 2022-11-10 at 7 54 59 AM" src="https://user-images.githubusercontent.com/1976742/201110768-59a3f6e4-4aef-4740-81df-e756339dda0e.png">

**Comment by rahaeli** [comment]
Hmm. We do, albeit rarely, get cases we need to do troubleshooting on where someone is having frequent but irregular attempts checking out and the failed attempts are attached to an old/open cart (if they cleared the cart and tried again) and it's valuable to look up past failures. 

Two options I can see that would achieve the goal of "less crud in the table" while still preserving some useful information, implement whichever is easier: 

1. Dump open carts created by logged-out accounts every 30 days, but save open carts from logged-in accounts for 180 days, or,

2. Dump open carts that don't have a failed payment attempt attached to them, while keeping open carts that did have a payment attempt made (that failed)

**Comment by kareila** [comment]
To clarify, an "open" cart is one that hasn't completed the checkout process. So your case 2 doesn't apply - any cart with a failed payment should be in the "checkout completed" or "payment pending" state.

**Comment by rahaeli** [comment]
Oh, I thought they all counted as open since they show as just "open" when looking up payments! Lemme see if I can find a cart # that has the thing I mean

**Comment by rahaeli** [comment]
Okay, nevermind, I found a cart that did the thing I was thinking of and I was totally wrong, please disregard me. Next time I will confirm what I was thinking before I waste your time 😂 Deleting open carts after 30 days is fine, then!

**Comment by kareila** [comment]
@zorkian just fixed this in c6c12929c7f7cf2b3504a838b0658b3880bb7e21 :)
