### ISSUE TITLE
Make "Generate API key" more discoverable

### ISSUE THREAD

**Issue by alierak** [dreamwidth/dreamwidth#3021]
At the moment it's a bit difficult to navigate to /manage/emailpost to find where to generate an API key. If you use the menu (Organize / Manage Account / Mobile tab), that takes you to /manage/settings?cat=mobile, where there is a link to "Advanced Setup Options" at the bottom of the Email Posting section. The layout and location of the link sort of implies that it's only going to be related to email posting, and it's not at all obvious that will be the place to generate an API key.

**Comment by momijizukamori** [comment]
Honestly if you have an idea of where to shove it, I'm all ears! I think my original logic was that it's kiiiiind of like post-by-email keys, and I couldn't think of a better spot at the time.
