### ISSUE TITLE
Text editor does not create <p>s, but uses <br><br>s instead

### ISSUE THREAD

**Issue by TarryDan** [dreamwidth/dreamwidth#3027]
Not an urgent issue, but would conform better to css standards & have a better user experience.

When I write a post in the Rich Text editor, it interprets gaps between paragraphs by adding <br><br>. Ideally, it should interpret them as paragraphs instead, adding </p><p>.

**Comment by rahaeli** [comment]
Hi there! 

The existing rich text editor is Extremely Deprecated for many reasons, and we are no longer making changes to it as part of our ongoing effort to get the beta Create Entries page out of beta. If you'd prefer while we work, you can use Markdown by typing "!markdown" at the beginning of your post, even in the non-beta update page.

(Also, I'm assuming you mean &lt;br> vs &lt;p> (Github ate your HTML), but assuming you did -- it's actually a really hard problem to correctly parse input for when to add/close a block level tag. We don't get into it as a matter of policy; our rich text policy is "select an available rich text editor package and make as few changes as possible".)

**Comment by rahaeli** [comment]
(I forgot to add the <a href="https://stackoverflow.com/questions/1732348/regex-match-open-tags-except-xhtml-self-contained-tags/1732454#1732454">obligatory Stackoverflow link</a> about parsing HTML with regular expressions)
