### ISSUE TITLE
make certain sections on profile invisible until user has confirmed email

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dreamwidth#3051]
Users should be able to edit their profile even before they've confirmed their email, but until they've confirmed their email, anything they enter in the bio and website links should only display to them while logged in, not to any other user. (Ideally, with a "not visible" icon -- the same icon as the one we use for "visible only to you" is fine -- with a link to https://www.dreamwidth.org/support/faqbrowse?faqid=3, which we will then edit to say that your profile bio and website link will not be visible until you've confirmed your email address.)

**Comment by kareila** [comment]
Closing this (with permission) as conflicting with #2795 as well as #3067.
