### ISSUE TITLE
Directory search: remove "age" as a search option

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dreamwidth#3065]
I've been looking at the directory search page lately for the first time pretty much since we forked from LJ because it's been helpful in spammer fighting, and having actually looked at the search options, it's made me realize that we absolutely need to stop including "age" as an option at all, on user safety grounds. (The directory search runs off the age specified on the profile, which is 100% optional to include and does not have to be a user's real age, and often isn't thanks to RP accounts and the like, but it's still a ridiculously basic violation of user-safe design 101 to include the search option at all.)

**Comment by pauamma** [comment]
Noting that the following files and directories (among others?) may need changes to completely remove this misfeature and plow salt into the ground where it stood:
- views/directory
- cgi-bin/DW/Controller/Search/Directory.pm
- cgi-bin/LJ/Directory/
- cgi-bin/LJ/Directory/Constraint/
- cgi-bin/LJ/Directory/SetHandle/
- t/directorysearch*
- bin/worker/directory-meta

**Comment by pauamma** [comment]
Tentative test plan:
- web form no longer display the option or pass it to the back end.
- back end no longer process it if it gets a hand-edited URL
- APIs ignore or refuse it

**Comment by momijizukamori** [comment]
@pauamma I don't have any implementation for directory search (and it's not on my current to-do list for API things anyway).

Are you thinking of tackling this, or should I poke at it some?

**Comment by pauamma** [comment]
I'm thinking of poking at it if no one beats me to it, but I've been thinking of that for over 4 months, so feel free to g-r-a-b it if it's urgent.

**Comment by kareila** [comment]
Go for it!
