### ISSUE TITLE
Clean up now-redundant S2 code for header navlinks

### ISSUE THREAD

**Issue by momijizukamori** [dreamwidth/dreamwidth#3073]
Follow-up from #674 - with the change, a number of the layouts that had header navlinks already now have redundant code. Which isn't harming anything, but makes stuff more confusing to read. For any of the following layouts, if the `Page::print()` function matches exactly what's in core2, it can be removed, along with the navlinks module override property. The core2 version appears here: https://github.com/dreamwidth/dreamwidth/blob/main/styles/core2.s2#L4902

- [ ] Bannering
- [ ] Bases
- [ ] Basic Boxes
- [ ] Boxes and Borders
- [ ] Crossroads
- [ ] Database
- [ ] Dusty Foot
- [ ] Fantaisie
- [ ] Five AM
- [ ] Heads Up
- [ ] Hibiscus
- [ ] Lefty
- [ ] Librarian's Dream
- [ ] Marginless
- [ ] Modular
- [ ] Motion
- [ ] Negatives
- [ ] Nouveau Oleanders
- [ ] Paletteable
- [ ] Patsy
- [ ] Pattern
- [ ] Planet Caravan
- [ ] Practicality
- [ ] Seamless
- [ ] Skittlish Dreams
- [ ] Strata
- [ ] Summertime
- [ ] Sunday Morning
- [ ] Tectonic
- [ ] Transmogrified
- [ ] Wide Open

**Comment by cmho** [comment]
Checked all the layouts, and the ones duplicating ::print() exactly were:
* Bannering
* Hibiscus
* Marginless
* Modular
* Nouveau Oleanders
* Palettable
