### ISSUE TITLE
antispam support category email alias missing

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dreamwidth#3075]
We can send email from antispam@dreamwidth.org and we have the supportcat set up, but it looks like the email alias wasn't turned on when the supportcat was created. I've added the alias through /admin/supportcat and am opening this to remind me to test it.

**Comment by rahaeli** [comment]
Test message bounced, will try again tomorrow to see if it just needs nightly maintenance to run

**Comment by rahaeli** [comment]
Account was blank and hadn't been logged into in ages, so I renamed it and emailed them a free rename token. Email sent to address still bounced. Edited the supportcat again to see if that would work, email still bounced, will try again tomorrow after maintenance

**Comment by rahaeli** [comment]
(yes I remembered to put it into reserved-usernames this time)

**Comment by alierak** [comment]
Working now - it needed a local postfix alias on the mail server.
