### ISSUE TITLE
URL blocklist for HTML cleaner

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dreamwidth#3080]
I give up. I've resisted doing this for 15 years, because if you keep a list of "domains you will be suspended for posting links to" and anyone finds out any of the domains on the list they will make it a fun and exciting game to get other people to post the links that will get their account instant-suspended, but we are well past the point where cleaning up after accidental misfires will be signficantly, signifcantly less work than continuing to suspend the dozens of accounts daily that are spamming for the same domains over and over again.

The system must:

* attach "can edit the list" to a new priv siteadmin:spamblocklist 
* create a new admin system whereby someone with siteadmin:spamblocklist can add a domain to the blocklist or edit/remove previous items from the blocklist
* do wildcard matching so you can specify "spamdomain.com" on the list and it will match any URL at that domain
* add a hook that will scan entries, comments, profile bios, profile URLs in the "website" field of the profile and icon keywords (a depressing number of spam accounts add spam links in the icon keywords)
* if any of the scanned items contain any string that matches a domain on the blocklist, suspend the account immediately
* log to statushistory with a suspend message of "auto-suspend for matching domain blocklist: spamdomain.com"
* have the 'admin' field of the statushistory logger be some unique string that we can search for on /admin/statushistory like 'blocklistmatch' or something 

Not necessary but would be nice: if the suspend message could include where the blocklist match was ('entry: 11434.html', 'profile bio', 'icon keyword', etc). It should check for the bare string, not just in a &lt;a href> tag, because a lot of these spambots use Markdown, BBCode, etc, etc, even when we don't support the text markup format, or just use a bare URL that autolinks.

**Comment by momijizukamori** [comment]
Leaving this as a note for future implementer (which may or may not be me) - [this is the function to call for suspend](https://github.com/dreamwidth/dreamwidth/blob/3e5210f8342c56d45f919301ad4b65fa562d9d77/cgi-bin/LJ/User/Account.pm#L494)

**Comment by momijizukamori** [comment]
Okay, working on the hook side of this - while you can pass a string instead of a user to the suspend command and it won't error, it also won't save it in the admin column (leaving that blank for these entries)

Also we probably want to cache the list fairly heavily for performance.

**Comment by kareila** [comment]
We could create a special user account i.e. `spamblocklist` and assign the events to them via a config variable that tells the site which account to use for that purpose.

**Comment by rahaeli** [comment]
That works (make it dw-spamblocklist so we don't have to worry about *someone* forgetting to put it in the reserved-usernames list like *someone* did with the antispam@ alias) (it's me, I'm someone)

**Comment by rahaeli** [comment]
It's also okay to cache it for like up to a day, we almost never run the spam queue more than once a day and a 24h lag wouldn't hurt too much

**Comment by rahaeli** [comment]
The system user would work, I was just thinking a unique user would let us easily search in statushistory but I don't think anything else in statushistory gets logged from system!
