### ISSUE TITLE
don't add journal/comm to "recently active" on stats if the entry is not public

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dreamwidth#3092]
The "recently active" journal and community sections on https://www.dreamwidth.org/stats will bump a journal/comm even if the entry that was just posted is locked, filtered, or private. It should only bump the account for public entries, since the point of those sections are to steer people to "people who are publicly active on the site".

**Comment by kareila** [comment]
I don't think is possible without a database update.

The current code isn't examining entries at all. It's keying off of the value stored in the `timeupdate` column of the `userusage` table and then skipping any accounts that aren't currently visible.

I think that to do what you want, we would need to add another column just for the time of the most recent public entry, i.e. `timeupdate_public`.

**Comment by alierak** [comment]
And if you posted a public entry and then later changed it to private, that would need recalculating.

**Comment by kareila** [comment]
Technically true, but if we're just using this for stats, I think a "best effort" is good enough here. It would still be an improvement in terms of how many of the accounts listed actually have recent public entries.

**Comment by rahaeli** [comment]
Yeah, best effort is good enough (currently the same thing happens if you post an entry and then delete it: still listed, no actual entry present).
