### ISSUE TITLE
cleanup from the interests decrement overflow bug

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dreamwidth#3106]
Still haven't been able to figure out what's causing it, but the follow interests need their count reset:

animu&mango | 16777215
smashing pre-conceived notions of feminity | 16777215
minimal electro | 16777215
olivia/astrid | 16777215
sueyoshi shuuta | 16777215
george yepes | 16777215
american dragon: jake long | 16777215
the carlos quentin | 16777215
snoo | 16777215
gala | 16777215

**Comment by kareila** [comment]
see also #3054 (some duplicates here)
