### ISSUE TITLE
Add Media Query support to all base layouts

### ISSUE THREAD

**Issue by momijizukamori** [dreamwidth/dreamwidth#3110]
The core2base layouts have functionality to expose a media query setting in the wizard, which allows users to easily set media breakpoints for collapsing the layout tidily on smaller screens. It would be great to have this support in all our base layouts.

Relevant bits of code:
```
    property use medium_breakpoint_width;
    property use large_breakpoint_width;
```
which goes in `propgroup presentation` and then
```
    var string small_media_query = generate_small_media_query();
    var string medium_media_query = generate_medium_media_query();
    var string large_media_query = generate_large_media_query();
``` 
in ` Page::print_default_stylesheet()`. These can then be used in `@media` CSS rules, such as [this one](https://github.com/dreamwidth/dreamwidth/blob/main/styles/core2base/layout.s2#L442). Styles that don't use the typical columns structure will probably also need additional CSS so they style nicely at smaller sizes.

**Comment by cmho** [comment]
todo:
[x] Venture
[ ] EasyRead (sort of—it's already pretty mobile friendly, but just to check)
[ ] Goldleaf
[ ] Zesty (it's one column but also needs refurbishment probably)
