### ISSUE TITLE
Text::Fuzzy wants to correct fastmail.com to hotmail.com or something

### ISSUE THREAD

**Issue by cmho** [dreamwidth/dreamwidth#3118]
Admittedly I'm probably one of very few Fastmail users on the site so this is definitely low priority, but considering I'm a roleplayer it's a little annoying to have to retype my email address and tick the "yes for real this is my email" box every time. Can we add it to the common domains list or something?

**Comment by momijizukamori** [comment]
If we decide to do this, the code block in question is here: https://github.com/dreamwidth/dreamwidth/blob/d02ce7509b96c191dfefe5c601d7bd2b0359a223/cgi-bin/LJ/User/Message.pm#L546
