### ISSUE TITLE
Add a non-submit button to HTMLControls & FormHTML

### ISSUE THREAD

**Issue by momijizukamori** [dreamwidth/dreamwidth#3152]
Because sometimes you want a button that's just a button, and it would be nice to have a standardized way to make them with the rest of our input types. Should be the same as the submit button code but explicitly set `type=button` on the element.

FormHTML - https://github.com/dreamwidth/dreamwidth/blob/e11cd13e0714c63b2f2c407612ebf62e06b59058/cgi-bin/DW/Template/Plugin/FormHTML.pm#L322

HTMLControls - https://github.com/dreamwidth/dreamwidth/blob/e11cd13e0714c63b2f2c407612ebf62e06b59058/cgi-bin/LJ/HTMLControls.pm#L487

(FormHTML is wrapper functions around HTMLControls so they can be used in Template Toolkit files)

**Comment by kareila** [comment]
`html_submit` already takes a `type` option - check L520 for 'reset' and do the same thing for 'button'
