### ISSUE TITLE
add caste to Diversity Statement and update CC license

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dreamwidth#3154]
From a suggestion: add "caste" to https://www.dreamwidth.org/legal/diversity. It should go between "ethnicity" and "size" in the sentence: 

> We welcome people of any gender identity or expression, race, ethnicity, size, nationality, sexual orientation, ability level, neurotype, religion, elder status, family structure, culture, subculture, political opinion, identity, and self-identification.

And while you're in there, update the CC license from 3.0 BY-SA to 4.0 BY-SA: https://creativecommons.org/licenses/by-sa/4.0/ (the image can stay the same, just update the text to read "This document is usable under a Creative Commons 4.0 BY-SA license." and change the link to https://creativecommons.org/licenses/by-sa/4.0/ instead of 3.0.

**Comment by pauamma** [comment]
claim

While there:
- I assume that by "the image can stay the same", you meant "the image and its alt text both *should* stay the same".
- I'm bumping the copyright years but not touching the "this isn't free" blurb even though it's no longer correct.

Before I push the change, let me know whether (and how) either is incorrect.
