### ISSUE TITLE
spam autosuspender not looking at profile edits done as part of account creation

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dreamwidth#3167]
Discovered while I was adding some domains to the spam autosuspender and testing it by creating a fake spam account: it doesn't trigger if you fill out your profile as part of the immediate post-registration wizard, only if you edit your profile after you've gotten out of the wizard and use /manage/profile instead. (Ah, the joys of discovering there's yet another godamn code path that does the thing.)

**Comment by kareila** [comment]
Fixed by #3169
