### ISSUE TITLE
change_journal_type console command needs fixing up to reflect password changes

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dreamwidth#3208]
The change_journal_type console command (used to convert a community to a personal journal) takes a second account as the account the newly-converted account should inherit certain properties from, as such:

> change_journal_type person target_community parent_username

Previously, running the command would convert target_community from journaltype: C to journaltype: P, set target_community to the same email address as parent_username, and set target_community to the same password as parent_username (and we'd tell people to immediately change the password). It looks like after the 2020 password changes, we can no longer have target_community inherit the same password as parent_username and have it work, which makes perfect sense, but we should fix up the code and make it stop trying to.

Running the command should continue to convert target_community from journaltype: C to journaltype: P and set target_community to the same email address as parent_username, but it should set a randomly-generated password and immediately trigger a password reset email (after changing the email address, of course).

**Comment by kareila** [comment]
Past me already did this in #2674.

**Comment by rahaeli** [comment]
sweet, that was just my mistake then!
