### ISSUE TITLE
profile icon github.png is invisible on black background

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dreamwidth#3213]
I don't think we can support different profile icon images in different site skins, but maybe we can make it white-on-black instead of transparent-on-black?

**Comment by cmho** [comment]
![github](https://github.com/dreamwidth/dreamwidth/assets/267841/ecbbdfcf-43e0-4abe-a5fd-ae6e924cde99) 🤔 like this?

**Comment by kareila** [comment]
Yes exactly! 😎
