### ISSUE TITLE
upon further review, LJ::Directory::Constraint::ContactInfo needs to go away

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dreamwidth#3222]
In #3218 I rearranged some display code that was only being used in the "IM Info" site search, but I had to feed it a fake set of userids in order to test it because LJ::Directory::Constraint::ContactInfo wasn't returning any useful results.

A closer look reveals why:

```
    # FIRST: check whether we get matches based on IM services
    foreach my $service (qw(icq jabber skype google_talk)) {
        my $p = LJ::get_prop( "user", $service );
```

Aside from being painfully dated, this will straight up stop working once #3180 moves the account names out of userprops into a separate database table.

```
    # SECOND: check for lj jabber matches
    if ( $self->screenname =~ /(.+)\@$LJ::USER_DOMAIN$/ ) {
        push @uids, LJ::get_userid($1);
```

... and this is functionally identical to the "Site and Account" search, except with typing in `username@dreamwidth.org` instead of just `username`.

I propose two possible solutions:

1. Kill off the "IM Info" site search completely. 🔪 
2. Replace it with something that will search the new "other accounts on profile" database table once it gets merged.

**Comment by rahaeli** [comment]
I am okay with pulling out the code machete and not replacing it.
