### ISSUE TITLE
"current theme" widget got updated for homepage but is now harder to read on /customize

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dreamwidth#3265]
First reported here: https://dw-maintenance.dreamwidth.org/92733.html?thread=4201277#cmt4201277

Homepage version:
<img width="360" alt="Screenshot 2023-08-04 at 11 08 53 PM" src="https://github.com/dreamwidth/dreamwidth/assets/1976742/341ebee1-db04-454d-ab09-9f7c641d1225">

Style select version: 
<img width="347" alt="Screenshot 2023-08-04 at 11 09 07 PM" src="https://github.com/dreamwidth/dreamwidth/assets/1976742/48ff6ac6-aa5d-4bc7-9579-b74c70e7981d">

I believe the primary complaint is that the text on the lower right is smaller than before. The /customize page doesn't have Foundation styling, but perhaps some equivalent CSS could be applied in this one spot to make that text more legible...?

**Comment by mustafaazad03** [comment]
is this issue open for all ??
Can I try to contribute ??

**Comment by momijizukamori** [comment]
@mustafaazad03 go for it, though I wouldn't spend super long on it - hopefully that view is going away for good in the next few months (because it will all be converted to use Foundation)
