### ISSUE TITLE
Firefox inappropriately keeping items in inbox checked across refresh

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dreamwidth#3297]
Confirmed on Firefox 109.0.1 through 119.0 (current) on Mac. Steps to reproduce:

1. Load https://www.dreamwidth.org/inbox/
2. Check some, but not all, notifications
3. Hit "Delete selected"
4. After the page refreshes with just the previously-unchecked items left undeleted, refresh the inbox to get the full 15 item view

Upon refresh, the notifications that are in the same position as the previously-checked-and-deleted items were are checked (and shouldn't be). In other words, if you select and deleted items 1, 3, 6, 11, and 12 of the 15 items displayed on the page, then refresh the page, the new items 1, 3, 6, 11, and 12 are checked, whether they're newly loaded or items that were previously on the page.

**Comment by momijizukamori** [comment]
Is this the beta inbox, or the original one? Beta had code put in specifically for this type of issue so if it's not working any more, I'll have to do some digging.

**Comment by rahaeli** [comment]
Ah, fuck me, I thought I had the beta enabled and it turns out I didn't notice I didn't. Turned it on and it isn't doing the thing, so I'll close.
