### ISSUE TITLE
create entries beta: icon choice not autosaved

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dreamwidth#3309]
Reported by a user, reproduced by me in Chrome 119.0.6045.123 and Firefox 119.0.1: writing a draft entry and selecting anything other than default icon, then closing the window after autosave and following the prompt to restore the draft, reverts the restored draft to default icon. Looks like it's not saving the icon information.

**Comment by momijizukamori** [comment]
For reproduction testing - was setting the icon the last thing you did? It looks like setting the icon doesn't fire the backend save, but if something else fires it (like adding a tag), the icon info is included and restored. I remember having some frustrations trying to hook the icon events properly - I'll do some more debugging, but I want to make sure we don't have multiple issues here.

**Comment by momijizukamori** [comment]
Feel free to ping me if your bug is actually a different one than this!
