### ISSUE TITLE
create entries beta: finish integrating sticky entries

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dreamwidth#3310]
Reported by user in dw-beta here: https://dw-beta.dreamwidth.org/13896.html?thread=580936#cmt580936 and verified by Yrs Trly: if you edit a sticky entry with the Create Entries beta enabled, the "make entry sticky" box is checked and the browser makes an effort to make the checkbox uneditable. Some brief searching shows that we had problems in issue #1343 with things getting unstickied, but I think we just never finished implementing the "make a sticky entry unsticky" in the beta update page overall. People should be able to unsticky an entry by editing the entry and untickying the box!

**Comment by momijizukamori** [comment]
Poking around, I think https://github.com/dreamwidth/dreamwidth/blob/main/cgi-bin/DW/Controller/Entry.pm#L599 needs to copy over the `sticky_select` value so that this clause actually runs: https://github.com/dreamwidth/dreamwidth/blob/main/cgi-bin/DW/Controller/Entry.pm#L599
