### ISSUE TITLE
Embeddings on Mastodon show a captcha request

### ISSUE THREAD

**Issue by pseudomonas** [dreamwidth/dreamwidth#3346]
When a link to Dreamwidth is shared on (in this case) mastodon . social , the preview shows a captcha request. This seems to occur for any link to any Dreamwidth post.

![image](https://github.com/dreamwidth/dreamwidth/assets/2255067/858e156a-5a98-44ac-ad13-456d806854f8)

Is there a way that either the captcha page could include the relevant metadata snippet (and a relevant image from the post), or that the fetchers from known mastodon servers could be whitelisted, or some combination of those?

**Comment by rahaeli** [comment]
The standard answer for all of these is that if you can find a list of all the IP addresses of instances, we can add them to the exceptions list, but we aren't going to spend effort looking for it.
