### ISSUE TITLE
JS(?) issue on Edit Tags page

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dreamwidth#3359]
https://www.dreamwidth.org/support/see_request?id=48875

As described: when using the Edit Tags page and clicking to add an existing tag that contains an apostrophe, everything following the apostrophe gets dropped from the tag text. Hand-typing or copy-pasting the name of the tag works as expected.

**Comment by momijizukamori** [comment]
that does sound like a JS issue, but - looking at https://github.com/dreamwidth/dreamwidth/pull/3316/files when I converted the page, I didn't rewrite the JS (which has not, in fact, been touched in 14 years). So something with the old code is interacting weirdly with having the full foundation JS on the page.

(honestly tempted to just rewrite it with the interface we have for tags on the new entry page...)

**Comment by kareila** [comment]
Fixed by #3365
