### ISSUE TITLE
theme chooser widget not working correctly with communities

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dreamwidth#3362]
Multiple reports from people who are trying to choose new styles for their communities and are having them applied to their personal journals instead. @momijizukamori thinks it's a bug from the theme chooser widget conversion.

**Comment by momijizukamori** [comment]
So digging around it looks like I didn't actually get to the ThemeChooser widget yet, which means it's probably a weird interaction somewhere else - https://github.com/dreamwidth/dreamwidth/pull/3331/files and https://github.com/dreamwidth/dreamwidth/pull/3321/files are the most likely places for the problem to have happened in, I think.

**Comment by incantatem1** [comment]
Oh, so other people noticed this as well, good to know! I'm glad it's not browser being f*****d or whatever...
