### ISSUE TITLE
Edit Tags success message channeling Kool-Aid Man

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dreamwidth#3371]
In my testing, saving changes on the Edit Tags page would take you back to the entry whose tags were being edited, but then the "Tags successfully updated" success message would barge in at the top of the next page that had the appropriate div - eg. when loading Edit Tags again, but I also saw it appear on top of the success page when testing Manage Circle.

**Comment by momijizukamori** [comment]
Fixed in #3373
