### ISSUE TITLE
update Gift Paid Time profile link to use new shop url

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dreamwidth#3379]
From support: "It looks like when I click to gift a user paid time from their profile, the link still points to dreamwidth.org/shop and winds up just redirecting to the shop itself instead of bringing over the parameters and filling everything out for me."

**Comment by alierak** [comment]
This is coming from cgi-bin/DW/Logic/UserLinkBar.pm, sub buyaccount. It specifies a url starting with "shop/account" and then calls fix_link to turn it into an actual link. fix_link always prepends $LJ::SITEROOT/ if the url doesn't already start with $LJ::SITEROOT.
