### ISSUE TITLE
add Steam to profile/usertag

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dreamwidth#3387]
given a user [username], both profile link and username body can go to https://steamcommunity.com/id/[username] (there's an "all posts by X" option that would probably work better for the username body, but you can't predict the URL from the username alone, alas)

**Comment by sirilyan** [comment]
The `/id/[username]` thing isn't working for me, but there's a copyable link to `/profiles/[numeric_id]/`.

**Comment by sirilyan** [comment]
Aha. You do not get a `/id` link by default, you must add one within your profile.
