### ISSUE TITLE
Please put deck.blue on the allow-list for getting opengraph tags

### ISSUE THREAD

**Issue by frandroid** [dreamwidth/dreamwidth#3392]
I tried posting links to bluesky using the deck.blue client, and the opengraph preview hits a closed door:

![Screen Shot 2024-09-13 at 10 26 05 PM](https://github.com/user-attachments/assets/76faf0a9-ad8d-452b-b9a1-a9b14531aa65)

(Firefox on MacOS with a VPN, if that matters.)

I'm assuming that you have a list of white-listed sites that can grab OG data without having to pass a captcha...

**Comment by rahaeli** [comment]
This is actually a part of wider thing I am assembling the info for handing over to the correct folks, so I'm gonna close this issue because I'm tracking it in my personal system until I get what I need, but thank you!
