### ISSUE TITLE
standardize option to have navigation links at the top/in header

### ISSUE THREAD

**Issue by ninetyd** [dreamwidth/dreamwidth#674]
Several styles allow the navigation module to be displayed at the top or in the header area rather than in the sidebar.
This should be turned into a Core2 option and implemented in every style if possible.
As the scope of this bug is pretty big, don't hesitate to do this gradually or to work on one or two styles only. This doesn't have to be done all at once, or by only one person.

**Comment by Bronwenist** [comment]
Time to start learning more about dreamwidth. I'm claiming this.

**Comment by kareila** [comment]
Welcome! Please make sure you submit a CLA so that we can accept your contributions.

http://wiki.dreamwidth.net/wiki/index.php/CLA

**Comment by momijizukamori** [comment]
I know we had a spreadsheet of these once upon a time but of course I now cannot find it. So re-creating it here!

- [ ] *Abstractia*
- [x ] Bannering
- [x ] *Bases*
- [ x] Basic Boxes
- [ ] _**Blanket**_  
- [ x] Boxes and Borders
- [ ] *Brittle*
- [ ] Ciel
- [ ] ColorSide
- [ ] Compartmentalized
- [ ] Corinthian
- [ ] Crisped
- [ x] Crossroads
- [x ] Database
- [ ] *Drifting*
- [ x] Dusty Foot
- [ ] _**EasyRead**_
- [x ] Fantaisie
- [ x] Five AM
- [ ] Fluid Measure
- [ ] For The Bold
- [ ] Funky Circles
- [ ] Gold Leaf
- [ x] Heads Up
- [x ] Hibiscus
- [ ] Leftovers
- [x ] Lefty
- [ x] Librarian's Dream
- [ ] Line Up
- [ x] Marginless
- [ ] **Mobility**
- [ ] Modish
- [x ] Modular
- [ x] Motion
- [x ] *Negatives*
- [x ] Nouveau Oleanders
- [ x] Paletteable
- [ ] Paper Me
- [ x] Patsy
- [ x] Pattern
- [ x] Planet Caravan
- [ x] Practicality
- [ ] Refried Tablet
- [ x] Seamless
- [ x] *Skittlish Dreams*
- [ ] Snakes & Boxes
- [ ] Stepping Stones
- [ x] Strata
- [x ] Summertime
- [x ] *Sunday Morning*
- [ ] Tabula Rasa
- [* ] Tectonic
- [ ] Tranquility III
- [ x] *Transmogrified*
- [ x] **Trifecta**
- [ x] **Venture**
- [ x] Wide Open
- [ ] _**Zesty**_

Stuff in **bold** uses nonstandard module layouts and should probably not be touched. Stuff in *italics* is non-Tabula Rasa styles.
